### ISSUE TITLE
TEI Ant transformations fail with classpath errors in Oxygen-21.0

### ISSUE THREAD

**Issue by rvdb** [TEIC/oxygen-tei#30] opened 2019-02-27 15:48 UTC
ANT transformation scenarios in the TEI-bleeding framework don't work in Oxygen-21.0, due to classpath errors. For example, the "TEI P5 ODT" Ant transformation scenario throws following error:

    Executing:
    "c:\program files\oxygen xml editor 21\jre/bin/java" -Dfile.encoding=UTF-8 -Xmx256m -classpath "C:\Program Files\Oxygen XML Editor 21\tools\ant/lib/ant-launcher.jar" "-Dant.home=C:\Program Files\Oxygen XML Editor 21\tools\ant" org.apache.tools.ant.launch.Launcher -lib "C:\Program Files\Oxygen XML Editor 21\classes" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygen.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygenAuthor.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygenDeveloper.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygenEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygenAuthorEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygenDeveloperEclipse.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\resolver.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\xercesImpl.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\saxon9ee.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\saxon.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\xml-apis-ext.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\log4j.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\oxygen-basic-utilities.jar" -f "C:/Users/ron/AppData/Roaming/com.oxygenxml/extensions/v21.0/frameworks/https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odt/build-to.xml" "-DinputFile=C:\Users\ron\Desktop\test-oxygen.xml" "-DoutputFile=C:\Users\ron\Desktop/out/test-oxygen.odt" "-Dprofile=default" "-Dlang=en" "-Doxygenlib=C:\Program Files\Oxygen XML Editor 21/lib" "-Dwebhelp.trial.license=no"

    Buildfile: C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\stylesheet\odt\build-to.xml

    setup:
        [mkdir] Created dir: C:\Users\ron\AppData\Local\Temp\build2051649554

    odd:

    notodd:
         [echo] Converting C:\Users\ron\Desktop\test-oxygen.xml into C:\Users\ron\Desktop/out/test-oxygen.odt
         [echo] unzip ODT template
        [unzip] Expanding: C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\stylesheet\profiles\default\odt\template.odt into C:\Users\ron\AppData\Local\Temp\build2051649554
         [echo] Get names of graphics files and write an ant task
         [xslt] Processing C:\Users\ron\Desktop\test-oxygen.xml to C:\Users\ron\AppData\Local\Temp\build2051649554\copy.xml
         [xslt] Loading stylesheet C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\stylesheet\tools\makegraphicsanttask.xsl
         [xslt] Failed to load net.sf.saxon.TransformerFactoryImpl via the configured classpath, will try Ant's classpath instead.
         [xslt] Failed to process C:\Users\ron\Desktop\test-oxygen.xml

    BUILD FAILED
    C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\stylesheet\odt\build-to.xml:35: The following error occurred while executing this line:
    C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\stylesheet\common\teianttasks.xml:75: java.lang.ClassNotFoundException: net.sf.saxon.TransformerFactoryImpl
      at java.net.URLClassLoader.findClass(Unknown Source)
      at java.lang.ClassLoader.loadClass(Unknown Source)
      at java.lang.ClassLoader.loadClass(Unknown Source)
      at java.lang.Class.forName0(Native Method)
      at java.lang.Class.forName(Unknown Source)
      at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getFactory(TraXLiaison.java:425)
      at org.apache.tools.ant.taskdefs.optional.TraXLiaison.getSource(TraXLiaison.java:257)
      at org.apache.tools.ant.taskdefs.optional.TraXLiaison.readTemplates(TraXLiaison.java:309)
      at org.apache.tools.ant.taskdefs.optional.TraXLiaison.createTransformer(TraXLiaison.java:328)
      at org.apache.tools.ant.taskdefs.optional.TraXLiaison.transform(TraXLiaison.java:188)
      at org.apache.tools.ant.taskdefs.XSLTProcess.process(XSLTProcess.java:881)
      at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:419)
      at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
      at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      at org.apache.tools.ant.Task.perform(Task.java:348)
      at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
      at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
      at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      at org.apache.tools.ant.Task.perform(Task.java:348)
      at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:402)
      at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
      at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      at org.apache.tools.ant.Task.perform(Task.java:348)
      at org.apache.tools.ant.Target.execute(Target.java:435)
      at org.apache.tools.ant.Target.performTasks(Target.java:456)
      at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
      at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
      at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
      at org.apache.tools.ant.Main.runBuild(Main.java:857)
      at org.apache.tools.ant.Main.startAnt(Main.java:236)
      at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
      at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

    Total time: 0 seconds

    The process finished with exit code: 1

A different classpath error is thrown when executing the "jTEI PDF" Ant transformation scenario: 

    Executing:
    "c:\program files\oxygen xml editor 21\jre/bin/java" -Dfile.encoding=UTF-8 -Xmx256m -classpath "C:\Program Files\Oxygen XML Editor 21\tools\ant/lib/ant-launcher.jar" "-Dant.home=C:\Program Files\Oxygen XML Editor 21\tools\ant" org.apache.tools.ant.launch.Launcher -lib "C:\Program Files\Oxygen XML Editor 21\lib\resolver.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\xercesImpl.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\saxon9ee.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\log4j.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\fop.jar" -lib "C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\jtei_aux\trans" -lib "C:\Program Files\Oxygen XML Editor 21\lib\commons-logging-1.2.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\avalon-framework-api-4.3.1.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\avalon-framework-impl-4.3.1.jar" -lib "C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\jtei_aux\trans\pdf\lib\fontbox-2.0.8.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\batik-all-1.7.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\commons-logging-1.1.3.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\xmlgraphics-commons-1.5.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\commons-io-1.3.1.jar" -lib "C:\Program Files\Oxygen XML Editor 21\lib\avalon-framework-4.2.0.jar" -f "C:/Users/ron/AppData/Roaming/com.oxygenxml/extensions/v21.0/frameworks/https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/jtei_aux/trans/pdf/jtei-pdf.xml" transform-pdf "-Dcfd=C:\Users\ron\Desktop" "-Dcfne=test-oxygen.xml" "-Ddest.file.basename=test-oxygen" "-Dtransformations.base=file:/C:/Users/ron/AppData/Roaming/com.oxygenxml/extensions/v21.0/frameworks/https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/profiles/jtei" "-Dwebhelp.trial.license=no"

    Buildfile: C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\jtei_aux\trans\pdf\jtei-pdf.xml

    BUILD FAILED
    C:\Users\ron\AppData\Roaming\com.oxygenxml\extensions\v21.0\frameworks\https___jenkins.tei_c.org_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen\tei\xml\tei\jtei_aux\trans\pdf\jtei-pdf.xml:6: taskdef class org.apache.fop.tools.anttasks.Fop cannot be found
     using the classloader AntClassLoader[]

    Total time: 0 seconds

    The process finished with exit code: 1

Has Oxygen-21.0 introduced changes w.r.t. Ant classpaths that should be taken into account?

**Comment by lb42** [comment] 2019-02-27 15:51
The announcement for release 21 says "The TEI Schemas bundled with Oxygen 21 were updated to version 3.5 and the TEI Stylesheets were updated to version 7.47. " so they must have changed something somewhere. (I can't test it myself because my current licence -- for oxygen 17 --  doesn't work with release 21 :-()

**Comment by rvdb** [comment] 2019-02-27 16:16
Ah, thanks for the pointer, @lb42 . The shipped TEI transformations do work; lots of its classpath entries have been modified with wildcards, so things have been updated somewhere. Checking the github repo, this seems to have happened in the [`oxygen_integration`](https://github.com/TEIC/oxygen-tei/tree/oxygen_integration) branch. 

Shouldn't those changes be reflected in the [`oxygen-tei-bleeding`](https://jenkins.tei-c.org/job/oxygen-tei-bleeding/) build on Jenkins, then?

**Comment by lb42** [comment] 2019-02-27 16:33
Yes. Especially since odd2odd doesn't work properly without the bleeding edge framework, even after upgrading to release 21 (my comment above about the licence notwithstanding -- I do have a valid licence!)

**Comment by martindholmes** [comment] 2019-02-27 17:24
Council has an action for one of them to talk to Radu (I think) about the best way to move the plugin forward while simultaneously maintaining backward compatibility for old versions of Oxygen. It's complicated. It would be trivial to abandon old versions of Oxygen, but the general consensus is that one reason for the plugin is to maintain the ability to update TEI resources even when people can't afford to update their Oxygen license.

**Comment by lb42** [comment] 2019-02-27 17:27
I am confused. I thought the whole point of having a "bleeding edge" framework is that it *is* in touch with the bleeding edge (ouch) -- so expecting it also to be backwards compatible seems rather strange.

**Comment by raducoravu** [comment] 2019-02-28 06:39
We keep changes the name of the JAR libraries in the Oxygen "lib" folder so ant-based transformation scenarios need to be changed and the library references updated.
As @rvdb said, comparing the ".framework" files between the two branches should show how the library references changed. With enough library references added the transformation scenario can be made to work with both older and newer versions of Oxygen.
The support for using wildcards in references to libraries was added in Oxygen 18.0 so if you want to have the framework work with even older Oxygen versions you will need to manually specify a lot of JAR library references.

**Comment by rvdb** [comment] 2019-02-28 11:31
I can confirm that if the "bleeding edge" framework files (currently in the `master` branch) are replaced with the ones in the 
[`oxygen_integration`](https://github.com/TEIC/oxygen-tei/tree/oxygen_integration/oxygen-tei/frameworks/tei) branch, the "jTEI PDF" transformation mentioned in my first post does work in Oxygen-16.1 up to Oxygen-21.0.

The "TEI P5 ODT" and "jTEI ODT" transformations still require some classpath changes to make them work in Oxygen-16.1. This is the correct classpath:

    <String>${oxygenHome}/classes/</String>
    <String>${oxygenHome}/lib/oxygen.jar</String>
    <String>${oxygenHome}/lib/oxygenAuthor.jar</String>
    <String>${oxygenHome}/lib/oxygenDeveloper.jar</String>
    <String>${oxygenHome}/lib/oxygenEclipse.jar</String>
    <String>${oxygenHome}/lib/oxygenAuthorEclipse.jar</String>
    <String>${oxygenHome}/lib/oxygenDeveloperEclipse.jar</String>
    <String>${oxygenHome}/lib/oxygen-basic-utilities.jar</String>
    <String>${oxygenHome}/lib/resolver.jar</String>
    <String>${oxygenHome}/lib/xercesImpl.jar</String>
    <String>${oxygenHome}/lib/saxon9ee.jar</String>
    <String>${oxygenHome}/lib/saxon.jar</String>
    <String>${oxygenHome}/lib/*resolver*.jar</String>
    <String>${oxygenHome}/lib/*xerces*.jar</String>
    <String>${oxygenHome}/lib/*saxon*9*.jar</String>
    <String>${oxygenHome}/lib/*saxon*.jar</String>
    <String>${oxygenHome}/lib/xml-apis-ext.jar</String>
    <String>${oxygenHome}/lib/log4j.jar</String>
    <String>${framework(TEI P5)}/xml/tei/jtei_aux/trans/</String>

**Comment by raducoravu** [comment] 2019-10-25 06:14
👍  one more report here:
https://www.oxygenxml.com/forum/viewtopic.php?f=22&t=20820

**Comment by djbpitt** [comment] 2019-10-29 10:35
Bitten by this error (21.1, build 2019101513, MacOS), I followed the advice at Radu's link above (https://www.oxygenxml.com/forum/viewtopic.php?f=22&t=20820) to "Uninstall the add-on (Help->Manage add-ons) and use Oxygen's default bundled TEI framework support." ODD-to-Relax NG Compact nonetheless errors out with the messages below. For what it's worth, generating XHTML documentation works as expected. The most informative line seems to be:

```
Error: odd2odd.xsl: Source http://www.tei-c.org/Vault/P5/3.6.0/xml/tei/odd/p5subset.xml + tei:3.6.0 +  + file:/Users/djb/Downloads/tei_ms_repertorium_3-2.odd not readable
```

If I'm reading this correctly, it looks as if it may be failing to find something between the two plus signs. Advice welcome!

---

The two sets of error messages are:

```
Transformation failed. Fatal error during transformation using /Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl: Processing terminated by xsl:message at line 317 in odd2odd.xsl; SystemID: file:/Applications/Oxygen%20XML%20Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl; Line#: 317
```

and

```
Executing:

"/Applications/Oxygen XML Editor/.install4j/jre.bundle/Contents/Home/jre/bin/java" -Dapple.awt.UIElement=true -Dfile.encoding=UTF-8 -Xmx256m -classpath "/Applications/Oxygen XML Editor/tools/ant/lib/ant-launcher.jar" "-Dant.home=/Applications/Oxygen XML Editor/tools/ant" org.apache.tools.ant.launch.Launcher -lib "/Applications/Oxygen XML Editor/classes" -lib "/Applications/Oxygen XML Editor/lib/oxygen-basic-utilities.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-editor-variables-parser.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-resolver.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-xerces.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-saxon-9.jar" -lib "/Applications/Oxygen XML Editor/lib/saxon9-sql.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-saxon-6.jar" -lib "/Applications/Oxygen XML Editor/lib/xml-apis-ext.jar" -lib "/Applications/Oxygen XML Editor/lib/log4j.jar" -lib "/Applications/Oxygen XML Editor/lib/oxygen-patched-trang.jar" -f "/Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/rnc/build-to.xml" "-DdefaultSource=file:/Applications/Oxygen%20XML%20Editor/frameworks/tei/xml/tei/odd/p5subset.xml" "-DinputFile=/Users/djb/Downloads/tei_ms_repertorium_3-2.odd" "-Dlang=en" "-DoutputFile=/Users/djb/Downloads/out/tei_ms_repertorium_3-2.rnc" "-Doxygenlib=/Applications/Oxygen XML Editor/lib" "-Dprofile=default" "-Dwebhelp.trial.license=no"

Buildfile: /Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/rnc/build-to.xml

go:
     [echo] Do ODD expand processing (schema ${selectedSchema}) 
     [xslt] Processing /Users/djb/Downloads/tei_ms_repertorium_3-2.odd to /Users/djb/Downloads/tei_ms_repertorium_3-2.odd.processedodd
     [xslt] Loading stylesheet /Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl
     [xslt] Error: odd2odd.xsl: Source http://www.tei-c.org/Vault/P5/3.6.0/xml/tei/odd/p5subset.xml + tei:3.6.0 +  + file:/Users/djb/Downloads/tei_ms_repertorium_3-2.odd not readable
     [xslt] /Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl:317:0: Fatal Error! Processing terminated by xsl:message at line 317 in odd2odd.xsl
     [xslt] Failed to process /Users/djb/Downloads/tei_ms_repertorium_3-2.odd

BUILD FAILED
/Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/rnc/build-to.xml:30: The following error occurred while executing this line:
/Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/common/teianttasks.xml:389: Fatal error during transformation using /Applications/Oxygen XML Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl: Processing terminated by xsl:message at line 317 in odd2odd.xsl; SystemID: file:/Applications/Oxygen%20XML%20Editor/frameworks/tei/xml/tei/stylesheet/odds/odd2odd.xsl; Line#: 317

Total time: 1 second

The process finished with exit code: 1
```

**Comment by raducoravu** [comment] 2019-10-29 13:18
@djbpitt I can reproduce the problem on the ODD file downloaded from:
https://raw.githubusercontent.com/djbpitt/repertorium/master/tei_ms_repertorium.odd
The XSLT stylesheet "OXYGEN_INSTALL_DIR\frameworks\tei\xml\tei\stylesheet\odds\odd2odd.xsl" uses the doc-available method to see if a remote XML document is accessible:

http://www.tei-c.org/Vault/P5/3.2.0/xml/tei/odd/p5subset.xml

but the link is redirected to the "https" equivalent and the HTTP connection used by the XSLT processor cannot follow the redirect.

If you open the same odd2odd.xsl above, it has a parameter:

        <xsl:param name="defaultTEIServer">http://www.tei-c.org/Vault/P5/</xsl:param>

which should be changed to:

         <xsl:param name="defaultTEIServer">https://www.tei-c.org/Vault/P5/</xsl:param>

But this is problem not related to this particular issue, maybe you can add a separate issue for it.

**Comment by djbpitt** [comment] 2019-10-29 13:26
@raducoravu Thank you. I can confirm that changing the parameter in the _odd2odd.xsl_ file as you suggest fixes the problem. I'll open a separate issue, as you propose.

**Comment by skurzinz** [comment] 2020-06-05 12:54
I can confirm that in the case of the TEI P5 DOCX scenario that I just wanted to apply, changing 

> `<String>${oxygenHome}/lib/log4j.jar</String>` to  
> `<String>${oxygenHome}/lib/log4j*.jar</String>` 

does work in a copied scenario using Oxygen 22.1 and the latest oxygen-tei framework installed as an add-on. 

Thanks for documenting this issue here, especially thx to @raducoravu for pointing in the right direction with changed classpaths within Oxygen.

**Comment by martindholmes** [comment] 2020-06-05 14:59
I believe there are no more instances of 



    `<String>${oxygenHome}/lib/log4j.jar</String>`

in the oxygen-tei repo; they've all been changed to:

    `<String>${oxygenHome}/lib/*log4j*.jar</String>`

(with two asterisks rather than one). So I assume this is fixed in the bleeding-edge version of the plugin, and will be fixed in the next release of the stable plugin and the next release of Oxygen.

**Comment by raducoravu** [comment] 2020-06-09 06:18
My colleague @AlexJitianu added the wildcards in this pull request from what I remember: https://github.com/TEIC/oxygen-tei/pull/41

**Comment by martindholmes** [comment] 2020-06-09 14:35
@rvdb Can you confirm we can close this now, or is there still something that needs to be fixed?

**Comment by rvdb** [comment] 2020-06-12 13:01
@martindholmes I think this is looking good.

**Closed** 2020-06-12 13:03 UTC
Labels: bug, help wanted
