### ISSUE TITLE
Can't add TEI add-in to oXygen 22.1

### ISSUE THREAD

**Issue by wujastyk** [TEIC/oxygen-tei#51] opened 2021-04-17 21:30 UTC
Following the instructions at https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei-plugin.md , I get:

![image](https://user-images.githubusercontent.com/762246/115127171-b6bf5980-9f91-11eb-8a79-af0658a9d7f9.png)

```
ro.sync.net.protocol.http.HttpExceptionWithDetails: 404 Not Found for: https://github.com/TEIC/oxygen-tei/releases/download/oxygen-tei-4.2.2-7.51.2.zip
	at ro.sync.net.protocol.http.b.s.x(Unknown Source)
	at ro.sync.net.protocol.http.b.s.h(Unknown Source)
	at ro.sync.net.protocol.http.abstraction.n.p(Unknown Source)
	at ro.sync.net.protocol.http.abstraction.n.d(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.obtainResponse(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.getInputStream(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.t(Unknown Source)
	at ro.sync.net.protocol.http.WebdavHttpURLConnection.getHeaderField(Unknown Source)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
	at java.base/java.net.URLConnection.getContentLength(URLConnection.java:492)
	at ro.sync.net.protocol.https.WebdavHttpsURLConnection.getContentLength(Unknown Source)
	at ro.sync.exml.addons.ExtensionsSynchronizer.c(Unknown Source)
	at ro.sync.exml.addons.ExtensionsSynchronizer.downloadAddonsInformation(Unknown Source)
	at ro.sync.exml.addons.c.b.e.neeb(Unknown Source)
	at ro.sync.exml.addons.c.b.e.feeb(Unknown Source)
	at ro.sync.exml.addons.c.b.e$1.xgk(Unknown Source)
	at ro.sync.ui.application.lb.run(Unknown Source)

```

**Comment by sydb** [comment] 2021-04-17 21:46
Ack!!

Thank you for the bug report. I am pretty sure, despite the horrific looking message, that this just boils down to the file https://github.com/TEIC/oxygen-tei/releases/download/oxygen-tei-4.2.2-7.51.2.zip being missing. _Why_ it is missing is another story.

I also notice that the updateSite file has an incorrect description for this release, but that is both another issue and a minor one. This one, I think, is caused by a mis-match between the URL to the ZIP file in the updateSite file and on the GitHub release pages. Whether that mis-match is caused by a change in GitHub URLs, an error in the TEI “how to make an oXygen framework add-on” instructions, or an error by those of us who tried following those instructions yesterday I do not know, although I am highly suspicious that it is our error based on correct, but less than perfect documentation.

In any case, the correct URL seems to be https://github.com/TEIC/oxygen-tei/releases/download/v14.0.0/oxygen-tei-4.2.2-7.51.2.zip. (Note the “/v.14.0.0” that is missing from the one in the updateSite file.)

**Comment by martindholmes** [comment] 2021-04-17 22:16
I think this is caused by changes to the structure of the folders on the TEI server, I think. But @sydb there's no point in assigning it to me because I don't have login privileges on that server. I would suggest that someone who does just go in and fix that update file, and point at what the GitHub URL has become:

https://github.com/TEIC/oxygen-tei/releases/download/v14.0.0/oxygen-tei-4.2.2-7.51.2.zip

Then we can try to fix the XSLT.

**Comment by martindholmes** [comment] 2021-04-17 22:31
I've updated the XSLT to include the version number in the URL. But there is an additional problem which I think was caused by someone manually editing the updateSite.oxygen file at some point. The description element originally contained a generic description without any version information, and the XSLT just copied that from one release to the next. But at some point, the versions of TEI and Stylesheets got inserted into the description:

~~~~~
 <xt:description>Oxygen TEI plugin based on the latest stable release of TEI P5 (4.2.1) and the
      latest stable release of the TEI Stylesheets (7.51.1). To avoid conflict with builtin
      framework, please ensure that you have gone to Preferences-&gt;Document Type Association in
      oXygen and deactivated all the TEI frameworks that have "External" in the storage columns.
    </xt:description>
~~~~~

and the XSLT that generates the file is not expecting that, and just copies the old one to the new extension element. The XSLT that handles this doesn't currently know the versions of the TEI and Stylesheets, although it does of course know the zip file name, so it could parse them out of there, and construct the description anew each time. I'll have a go at making that work.

**Comment by hcayless** [comment] 2021-04-17 22:35
I've fixed the immediate problem by updating the URL and tested it by updating my Oxygen plugin locally. Checking the XSLT now.

**Comment by martindholmes** [comment] 2021-04-17 22:36
@hcayless I've fixed the XSLT in the last couple of commits. If you can test, that would be great.

**Comment by hcayless** [comment] 2021-04-17 22:44
@martindholmes you missed the 'v' before the tag name :-). Should work now.

**Closed by hcayless** 2021-04-17 22:44 UTC
Labels: bug

**Comment by sydb** [comment] 2021-04-17 22:45
Thank you, gentlemen.

**Comment by martindholmes** [comment] 2021-04-17 22:45
@hcayless Yes, just finally discovered that myself -- old home computer took ages to build it. Thanks for the fix. I think we're good now, no?

**Comment by wujastyk** [comment] 2021-04-18 21:32
Now works fine for me.  Thank you everyone!
