### ISSUE TITLE
ID-related error inside tei_math.rng

### ISSUE THREAD

**Issue by AlexJitianu** [TEIC/oxygen-tei#7] opened 2016-03-24 10:11 UTC
Hi,

I'm updating the TEI schema to be distributed with Oxygen v18.0 (which is to be released soon). I've taken the TEI schema version 2.9.1 and when opening and validating tei_math.rng inside Oxygen I get the following error:

conflicting ID-types for attribute "id" of element "mspace" from namespace "http://www.w3.org/1998/Math/MathML"

The error is related to this definition:

```
       <define name="tei_macro.anyXML">
          <element>
             <anyName>
                <except>
                   <nsName ns="http://www.tei-c.org/ns/1.0"/>
                   <name ns="http://www.tei-c.org/ns/Examples">egXML</name>
                   <nsName ns="http://www.w3.org/1998/Math/MathML"/>
                </except>
             </anyName>
             <zeroOrMore>
                <attribute>
                   <anyName/>
                </attribute>
             </zeroOrMore>
             <zeroOrMore>
                <choice>
                   <text/>
                   <ref name="tei_macro.anyXML"/>
                </choice>
             </zeroOrMore>
          </element>
       </define>
```

To fix the error we've added the MathML namespace in the except part:

```
       <define name="tei_macro.anyXML">
          <element>
             <anyName>
                <except>
                   <nsName ns="http://www.tei-c.org/ns/1.0"/>
                   <name ns="http://www.tei-c.org/ns/Examples">egXML</name>
                   <nsName ns="http://www.w3.org/1998/Math/MathML"/>
                </except>
             </anyName>
             <zeroOrMore>
                <attribute>
                   <anyName/>
                </attribute>
             </zeroOrMore>
             <zeroOrMore>
                <choice>
                   <text/>
                   <ref name="tei_macro.anyXML"/>
                </choice>
             </zeroOrMore>
          </element>
       </define>
```

Perhaps this is something that should be fixed in the official TEI schema too? The same error appears in tei_svg.rng too.

Best regards,
Alex

**Comment by martindholmes** [comment] 2016-03-24 12:41
Hi Alex,

I've asked the TEI Council to look at this; there have been changes in 
macro.anyXML recently which probably result in this problem.

The TEI is planning a release of version 3.0.0 of TEI and version 7.41.0 
of the Stylesheets next Tuesday, so if you're building for a subsequent 
release of Oxygen, it would be best to use that. There are products for 
those branches available here:

<http://teijenkins.hcmc.uvic.ca/job/Stylesheets-release-7.41.0/lastSuccessfulBuild/artifact/>

<http://teijenkins.hcmc.uvic.ca/job/TEIP5-release-3.0.0/lastSuccessfulBuild/artifact/P5/>

I'm not on Council now so I'm not sure whether they're going to release 
from those branches or from the master branch which also has builds in 
the Jenkins setup. If you can wait till after Tuesday, the releases 
should be done and all should be good. I'm going to check the MathML 
schemas from both those builds myself and see if they fail to validate; 
if they do, then I'll file a release-blocking bug.

Cheers,
Martin

**Comment by martindholmes** [comment] 2016-03-24 12:44
I've tested the tei_math.rng from the release branch:

<http://teijenkins.hcmc.uvic.ca/job/TEIP5-release-3.0.0/lastSuccessfulBuild/artifact/P5/release/xml/tei/custom/schema/relaxng/tei_math.rng>

and the problem is not there; however it is there in the master branch, 
which I presume is out of date.

Cheers,
Martin

**Comment by hcayless** [comment] 2016-03-24 12:46
I’m pretty sure that was fixed in dev a couple of months ago. We’ll be doing a release (3.0.0) next week, which will have the fix in it. Master is out of date, because we’ve switched to a Git Flow repo model. 

/**
 *  Hugh A. Cayless, Ph.D
 *  Chair, TEI Technical Council
 *  hugh.cayless@duke.edu
 *  Duke Collaboratory for Classics Computing (DC3)
 *  http://blogs.library.duke.edu/dcthree/
**/

**Comment by AlexJitianu** [comment] 2016-03-24 13:26
Hi Martin and Hugh,

Is good to know that is already fixed. I think we can wait 'till Tuesday. I'll try to make another update then and see how our tests run. Hopefully they wont find any issues (first releases can have problems).

Best regards,
Alex

**Comment by AlexJitianu** [comment] 2016-04-07 14:11
Hi,

I confirm that in version 3.0.0 the problem doesn't reproduce anymore. One additional small issue I've encountered: in tei_enrich.rng there are two Schematron patterns with the same id: tei_enrich-relatedItem-targetorcontent1-constraint-8

When validating with this schema you get an error: cvc-id.2: There are multiple occurrences of ID value 'tei_enrich-relatedItem-targetorcontent1-constraint-8'.

**Comment by martindholmes** [comment] 2016-04-07 16:01
Confirmed, here:

http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_enrich.rng

I'll raise this as a bug on the TEI repo. The rng file itself validates, despite the duplicate id; I guess it's not an xml:id so uniqueness is not enforced when validating the schema. It's not till the Schematron validation process compiles it that the duplicate id problem emerges.

**Comment by jamescummings** [comment] 2016-08-12 13:53
Hi. Is this really a problem with tei_enrich? It sounds like something is wrong in the processing. The only schematron rule inside tei_enrich is at https://github.com/TEIC/TEI/blob/dev/P5/Exemplars/tei_enrich.odd#L3099 
so this conflict must come from processing the ODD and getting this rule from full TEI?  
relatedItem was added to TEI after ENRICH, so ENRICH has moduleRef for all of core and then deletes what it doesn't need. 

I'd suggest that it should just delete relatedItem as well? thoughts?  

Though the question still remains as to why when processing tei_enrich.odd duplicate IDs are created...  In relatedItem.xml there is a constraintSpec with id of targetorcontent1 at https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/relatedItem.xml#L35 but I don't see where the other constraint comes from?! I think this schema may just be out of date?

**Comment by martindholmes** [comment] 2016-08-12 18:05
I've seen this duplicate id problem in one of my own schemas, and I've been meaning to raise a ticket for it. When I get to a decent internet connection I'll try to reproduce it and post a link to the ODD. If we can figure out what's common to these ODDs it should be a straightforward fix. One possibility is the occurrence of two constraints in the same constraintSpec, or something like that; Syd and I talked about that as a possible source of problems recently, but I can't remember the details and I'm on a horrible connection right now.

**Comment by martindholmes** [comment] 2016-11-18 21:26
I believe this is an effect of this Stylesheets issue:

https://github.com/TEIC/Stylesheets/issues/176

**Comment by hcayless** [comment] 2016-12-09 04:49
Already fixed, so closing

**Closed by hcayless** 2016-12-09 04:49 UTC
